# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 365b89ab24a90354603e5491e0d4c030d1768df4344fd21f7d9e59473522161006dce8797ad1665509582a2527fbf72dc54392e86558b60af463ada9e04cfab0

test:
  secret_key_base: 46d4bdf0ffed659059af6f89d2124de3bc2a4fec4e5e36da97407d7eb221b1f5b1396bc8260ea12dc38610d7fed7b9b7741163a53d2a6b4b44e942ea3a51cb7a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
